demos/billing/protected/models/Product.php
<?php

/**
 * This is the model class for table "{{products}}".
 *
 * The followings are the available columns in table '{{products}}':
 * @property integer $idprod
 * @property integer $idcateg
 * @property string $nameprod
 * @property string $priceprod
 * @property integer $idmanufacturer
 *
 * The followings are the available model relations:
 * @property Categories $idcateg0
 * @property Manufacturers $idmanufacturer0
 * @property ProdSale[] $prodSales
 */
class Product extends CActiveRecord
{
    /**
     * @return string the associated database table name
     */
    public static $currency = " MDL";

    public function tableName()
    {
        return '{{products}}';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('idcateg, idmanufacturer', 'numerical', 'integerOnly' => true),
            array('nameprod', 'length', 'max' => 100),
            array('priceprod', 'length', 'max' => 9),
            // The following rule is used by search().
            // @todo Please remove those attributes that should not be searched.
            array('idprod, idcateg, nameprod, priceprod, idmanufacturer', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'idcateg0' => array(self::BELONGS_TO, 'Categories', 'idcateg'),
            'idmanufacturer0' => array(self::BELONGS_TO, 'Manufacturer', 'idmanufacturer'),
            'prodSales' => array(self::HAS_MANY, 'ProdSale', 'idprod'),
            'orders' => array(self::HAS_MANY, 'Order', 'idprod'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'idprod' => 'ID',
            'idcateg' => 'Category',
            'nameprod' => 'Name',
            'priceprod' => 'Price',
            'idmanufacturer' => 'Manufacturer',
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     *
     * Typical usecase:
     * - Initialize the model fields with values from filter form.
     * - Execute this method to get CActiveDataProvider instance which will filter
     * models according to data in model fields.
     * - Pass data provider to CGridView, CListView or any similar widget.
     *
     * @return CActiveDataProvider the data provider that can return the models
     * based on the search/filter conditions.
     */
    public function search()
    {
        // @todo Please modify the following code to remove attributes that should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('idprod', $this->idprod);
        $criteria->compare('idcateg', $this->idcateg);
        $criteria->compare('nameprod', $this->nameprod, true);
        $criteria->compare('priceprod', $this->priceprod, true);
        $criteria->compare('idmanufacturer', $this->idmanufacturer);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    /**
     * Returns the static model of the specified AR class.
     * Please note that you should have this exact method in all your CActiveRecord descendants!
     * @param string $className active record class name.
     * @return Product the static model class
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public static function productSumByUser()
    {
        $orders = Order::model()->findAll([
            'condition' => 'iduser=:iduser AND idinv IS NULL',
            'params' => [':iduser' => Yii::app()->User->id]
        ]);
        $sum = 0;
        foreach ($orders as $order) {
            $initialPrice = $order->idprod0->priceprod;
            $productSale = Product::model()->productSale($order->idprod);
            $sum += $initialPrice - ($initialPrice * ($productSale / 100));
        }
        return $sum;
    }

    public static function productSale($id)
    {
        $prodsales = ProdSale::model()->find([
            'condition' => 'idprod=:idprod',
            'params' => [
                ':idprod' => $id
            ]
        ]);
        if (!is_null($prodsales))
            return $prodsales->idsale0->valuesale;
        return 0;
    }

    public static function productPriceWithSale($id)
    {
        $initialPrice = Product::model()->findByPk($id)->priceprod;
        $productSale = Product::model()->productSale($id);
        return $initialPrice - ($initialPrice * ($productSale / 100));
    }

    public static function productSaleUntil($id)
    {
        $prodsale = ProdSale::model()->find([
                'condition' => 'idprod=:idprod',
                'params' => [
                    ':idprod' => $id
                ]
            ]
        );
        return $prodsale->idsale0->startdate;
    }

    public static function productManufacturer($id)
    {
        return Manufacturer::model()->findByPk(Product::model()->findByPk($id)->idmanufacturer)->name;
    }

    public static function getProductsByCategoy($id)
    {
        $products = Product::model()->findAll([
            'condition' => 'idcateg=:idcateg',
            'params' => [':idcateg' => $id]
        ]);
        return $products;
    }
}

demos/billing/protected/controllers/OrderController.php
<?php

class OrderController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
//    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update', 'mine', 'remove', 'checkout', 'finish'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete'),
                'users' => array('*'),
            ),
            array('deny',  // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model = new Order;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Order'])) {
            $model->attributes = $_POST['Order'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->idcpi));
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Order'])) {
            $model->attributes = $_POST['Order'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->idcpi));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionRemove($id)
    {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('mine'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $dataProvider = new CActiveDataProvider('Order');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Lists my orders.
     */
    public function actionMine()
    {
        $dataProvider = new CActiveDataProvider('Order', [
            'criteria' => [
                'with' => ['idprod0'],
                'condition' => 'iduser=' . Yii::app()->User->id . ' AND idinv IS NULL',
                'order' => 'idprod0.priceprod ASC'
            ],
        ]);
        $this->render('mine', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
        $model = new Order('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Order']))
            $model->attributes = $_GET['Order'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    public function actionCheckout()
    {
        $dataProvider = new CActiveDataProvider('Order', [
            'criteria' => [
                'with' => ['idprod0'],
                'condition' => 'iduser=' . Yii::app()->User->id . ' AND idinv IS NULL',
                'order' => 'idprod0.priceprod ASC'
            ],
        ]);
        $this->render('checkout', array(
            'dataProvider' => $dataProvider,
        ));
    }

    public function actionFinish()
    {
        $orders = Order::model()->findAllByAttributes(['iduser' => Yii::app()->User->id]);
        $invoiceCreated = false;
        foreach ($orders as $order) {
            if ($order->idinv == "") {
                if (!$invoiceCreated) {
                    $invoice = new Invoice();
                    $invoice->aprobat = '0';
                    $invoice->save();
                    $idinv = $invoice->idinv;
                    $invoiceCreated = true;
                }
                $order->idinv = $idinv;
                $order->save();
            }
        }
        $this->redirect(['invoice/mine']);
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Order the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model = Order::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Order $model the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'order-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

demos/billing/protected/controllers/ProductController.php
<?php

class ProductController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    public function accessRules()
    {
        return [
            [
                'allow',
                'actions' => ['index'],
                'roles' => ['Guest']
            ]
        ];
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model = new Product;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Product'])) {
            $model->attributes = $_POST['Product'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->idprod));
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Product'])) {
            $model->attributes = $_POST['Product'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->idprod));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $dataProvider = new CActiveDataProvider('Product');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
        $model = new Product('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Product']))
            $model->attributes = $_GET['Product'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    public function actionBuy()
    {
        $order = new Order();
        $order->idprod = $_POST['idprod'];
        $order->iduser = Yii::app()->User->id;
        $order->date = date('Y-m-d');
        $order->save();
        $this->redirect(['product/index?new']);
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Product the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model = Product::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Product $model the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'product-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

demos/billing/protected/views/product/_form.php
<?php
/* @var $this ProductController */
/* @var $model Product */
/* @var $form CActiveForm */
?>

<div class="container-fluid col-md-4">

    <?php $form = $this->beginWidget('IActiveForm', array(
        'id' => 'product-form',
        // Please note: When you enable ajax validation, make sure the corresponding
        // controller action is handling ajax validation correctly.
        // There is a call to performAjaxValidation() commented in generated controller code.
        // See class documentation of CActiveForm for details on this.
        'enableAjaxValidation' => false,
    )); ?>

    <p class="note">Fields with <span class="required">*</span> are required.</p>

    <?php echo $form->errorSummary($model); ?>

    <div class="row">
        <div class="form-group">
            <?php echo $form->labelEx($model, 'idcateg'); ?>
            <?= CHtml::activeDropDownList($model, 'idcateg', CHtml::listData(Categories::model()->findAll(), 'idcateg', 'namecateg'), array('class' => 'form-control', 'prompt' => 'Select a category')); ?>
            <?php echo $form->error($model, 'idcateg'); ?>
        </div>
    </div>

    <div class="row">
        <div class="form-group">
            <?php echo $form->labelEx($model, 'idmanufacturer'); ?>
            <?= CHtml::activeDropDownList($model, 'idmanufacturer', CHtml::listData(Manufacturer::model()->findAll(), 'id', 'name'), array('class' => 'form-control', 'prompt' => 'Select a manufacturer')); ?>
            <?php echo $form->error($model, 'idmanufacturer'); ?>
        </div>
    </div>

    <div class="row">
        <div class="form-group">
            <?php echo $form->labelEx($model, 'nameprod'); ?>
            <?php echo $form->textField($model, 'nameprod', array('size' => 60, 'maxlength' => 100)); ?>
            <?php echo $form->error($model, 'nameprod'); ?>
        </div>
    </div>

    <div class="row">
        <div class="form-group">
            <?php echo $form->labelEx($model, 'priceprod'); ?>
            <div class="input-group">
                <?php echo $form->numberField($model, 'priceprod', array('min' => 1, 'max' => 9999999)); ?>
                <div class="input-group-addon"><?= Product::$currency ?></div>
            </div>
            <?php echo $form->error($model, 'priceprod'); ?>
        </div>
    </div>

    <div class="row buttons">
        <div class="form-group">
            <?php echo IHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
        </div>
    </div>

    <?php $this->endWidget(); ?>

</div><!-- form -->

demos/billing/protected/views/product/_search.php
<?php
/* @var $this ProductController */
/* @var $model Product */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'idprod'); ?>
		<?php echo $form->textField($model,'idprod'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'idcateg'); ?>
		<?php echo $form->textField($model,'idcateg'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'nameprod'); ?>
		<?php echo $form->textField($model,'nameprod',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'priceprod'); ?>
		<?php echo $form->textField($model,'priceprod',array('size'=>9,'maxlength'=>9)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'idmanufacturer'); ?>
		<?php echo $form->textField($model,'idmanufacturer'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

demos/billing/protected/views/product/_view.php
<?php
/* @var $this ProductController */
/* @var $data Product/Order */
$idprod = isset($data->idprod) ? $data->idprod : $data->idprod0->idprod;
$nameprod = isset($data->nameprod) ? $data->nameprod : $data->idprod0->nameprod;
$idcateg = isset($data->idcateg) ? $data->idcateg : $data->idprod0->idcateg;
$priceprod = isset($data->priceprod) ? $data->priceprod : $data->idprod0->priceprod;
$idmanufacturer = isset($data->idmanufacturer) ? $data->idmanufacturer : $data->idprod0->idmanufacturer;
$namecateg = isset($data->idcateg0) ? $data->idcateg0->namecateg : $data->idprod0->idcateg0->namecateg;
$idmanufacturer = isset($data->idmanufacturer0) ? $data->idmanufacturer0->name : $data->idprod0->idmanufacturer0->name;

$small = isset($small) && $small;
?>

<div class="<?= $small ? '' : 'col-sm-4'; ?>">
    <div class="thumbnail <?= $small ? "" : "product" ?>">
        <div class="caption">
            <h4><?= CHtml::link(CHtml::encode($nameprod), ['product/view', 'id' => $idprod]); ?></h4>
            <h4 class="<?=$small?"":"text-right"?>">
                <?php if (Product::productSale($idprod) != 0): ?>
                    <span class="text-danger"><s><?php echo CHtml::encode($priceprod); ?> MDL</s></span>
                    <?php echo Product::productPriceWithSale($idprod); ?> MDL
                <?php else: ?>
                    <?php echo CHtml::encode($priceprod); ?> MDL
                <?php endif; ?>
            </h4>
            <b><?php echo CHtml::encode(Product::model()->getAttributeLabel('idcateg')); ?>:</b>
            <?php echo CHtml::encode($namecateg); ?>
            <br/>

            <?php if (Product::productSale($idprod) != 0): ?>
                <b><?php echo CHtml::encode(Sales::model()->getAttributeLabel('sale')); ?>:</b>
                <?php echo Product::productSale($idprod); ?>%
                <br/>
            <?php endif; ?>

            <b><?php echo CHtml::encode(Product::model()->getAttributeLabel('idmanufacturer')); ?>:</b>
            <?php echo $idmanufacturer; ?>
            <br/>

            <div class="text-right">
                <?= isset($buy) && !$buy ? "" : CHtml::button('Buy',
                    [
                        'submit' => array('product/buy'),
                        'params' => [
                            'idprod' => $idprod
                        ],
                        'confirm' => 'Buy this product?',
                        'class' => 'btn btn-primary btn-md text-right btn-bottom'
                    ]
                ); ?>
            </div>
        </div>
    </div>
</div>

demos/billing/protected/views/product/admin.php
<?php
/* @var $this ProductController */
/* @var $model Product */

$this->breadcrumbs=array(
	'Products'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Product', 'url'=>array('index')),
	array('label'=>'Create Product', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#product-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Products</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'product-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'idprod',
		'idcateg',
		'nameprod',
		'priceprod',
		'idmanufacturer',
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

demos/billing/protected/views/product/create.php
<?php
/* @var $this ProductController */
/* @var $model Product */

$this->breadcrumbs=array(
	'Products'=>array('index'),
	'Create',
);

$this->menu=array(
	['label' => 'Create Product', 'url' => array('create')],
	array('label'=>'List Products', 'url'=>array('index')),
	array('label'=>'Manage Products', 'url'=>array('admin')),
);
?>

<h2>Create Product</h2>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

demos/billing/protected/views/product/index.php
<?php
/* @var $this ProductController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs = array(
    'Products',
);

$this->menu = array(
    ['label' => 'Create Product', 'url' => array('create')],
    ['label' => 'Manage Product', 'url' => array('admin')],
)
?>

<p>
    <?= isset($_GET['new']) ? 'The product was added to cart! <br> You can continue shopping or go to ' . CHtml::link('checkout', ['order/mine']) : "" ?>
</p>

<h2>All products</h2>

<?php $this->widget('zii.widgets.CListView', array(
    'dataProvider' => $dataProvider,    
    'itemView' => '_view',
    'htmlOptions' => [
        'class' => 'row'
    ],
    'summaryCssClass' => 'container-fluid text-right'
)); ?>

demos/billing/protected/views/product/update.php
<?php
/* @var $this ProductController */
/* @var $model Product */

$this->breadcrumbs=array(
	'Products'=>array('index'),
	$model->idprod=>array('view','id'=>$model->idprod),
	'Update',
);

$this->menu=array(
	array('label'=>'List Products', 'url'=>array('index')),
	array('label'=>'Create Product', 'url'=>array('create')),
	array('label'=>'View Product', 'url'=>array('view', 'id'=>$model->idprod)),
	array('label'=>'Manage Products', 'url'=>array('admin')),
);
?>

<h2>Update Product <?php echo $model->idprod; ?></h2>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

demos/billing/protected/views/product/view.php
<?php
/* @var $this ProductController */
/* @var $model Product */

$this->breadcrumbs = array(
    'Products' => array('index'),
    $model->nameprod,
);
?>
<div class="container-fluid">
    <div class="row">
        <h2><?php echo $model->idcateg0->namecateg . " " . $model->nameprod; ?></h2>
    </div>
    <div class="row">
        <h4><?= "<b>Manufacturer:</b> " . $model->idmanufacturer0->name ?></h4>
    </div>
    <div class="row">
        <h4><b>Price:</b>
            <?php if (Product::productSale($model->idprod) != 0): ?>
                <s class="text-danger"><?php echo $model->priceprod . Product::$currency; ?></s>
                <?php echo Product::productPriceWithSale($model->idprod) . Product::$currency; ?>
            <?php else: ?>
                <?php echo $model->priceprod . Product::$currency; ?>
            <?php endif; ?>
        </h4>
    </div>
    <?php if (Product::productSale($model->idprod) != 0): ?>
        <div class="row">
            <h4><b>Sale until:</b> <?= IHtml::idate(Product::productSaleUntil($model->idprod)) ?></h4>
        </div>
    <?php endif; ?>
</div>