demos/billing/protected/models/Order.php
<?php

/**
 * This is the model class for table "{{orders}}".
 *
 * The followings are the available columns in table '{{orders}}':
 * @property integer $idcpi
 * @property integer $iduser
 * @property integer $idprod
 * @property string $date
 * @property integer $idinv
 *
 * The followings are the available model relations:
 * @property User $iduser0
 * @property Products $idprod0
 * @property Invoices $idinv0
 */
class Order extends CActiveRecord
{
    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return '{{orders}}';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('iduser, idprod, idinv', 'numerical', 'integerOnly' => true),
            array('date', 'safe'),
            // The following rule is used by search().
            // @todo Please remove those attributes that should not be searched.
            array('idcpi, iduser, idprod, date, idinv', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'iduser0' => array(self::BELONGS_TO, 'User', 'iduser'),
            'idprod0' => array(self::BELONGS_TO, 'Product', 'idprod'),
            'idinv0' => array(self::BELONGS_TO, 'Invoices', 'idinv'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'idcpi' => 'ID',
            'iduser' => 'User',
            'idprod' => 'Product',
            'date' => 'Date',
            'idinv' => 'Invoice',
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     *
     * Typical usecase:
     * - Initialize the model fields with values from filter form.
     * - Execute this method to get CActiveDataProvider instance which will filter
     * models according to data in model fields.
     * - Pass data provider to CGridView, CListView or any similar widget.
     *
     * @return CActiveDataProvider the data provider that can return the models
     * based on the search/filter conditions.
     */
    public function search()
    {
        // @todo Please modify the following code to remove attributes that should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('idcpi', $this->idcpi);
        $criteria->compare('iduser', $this->iduser);
        $criteria->compare('idprod', $this->idprod);
        $criteria->compare('date', $this->date, true);
        $criteria->compare('idinv', $this->idinv);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public static function userInvoices()
    {
        $products = Order::model()->findAllByAttributes(array('iduser' => Yii::app()->User->id));
        $count = [];
        foreach ($products as $product) {
            if (isset($product->idinv) && !in_array($product->idinv, $count))
                $count[] = $product->idinv;
        }
        return count($count);
    }

    public static function getNrCartProducts()
    {
        return Order::model()->count(
            'iduser=:iduser AND idinv IS NULL',
            [
                ':iduser' => Yii::app()->User->id
            ]
        );
    }


    /**
     * Returns the static model of the specified AR class.
     * Please note that you should have this exact method in all your CActiveRecord descendants!
     * @param string $className active record class name.
     * @return Order the static model class
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }
}

demos/billing/protected/controllers/OrderController.php
<?php

class OrderController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
//    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update', 'mine', 'remove', 'checkout', 'finish'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete'),
                'users' => array('*'),
            ),
            array('deny',  // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model = new Order;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Order'])) {
            $model->attributes = $_POST['Order'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->idcpi));
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Order'])) {
            $model->attributes = $_POST['Order'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->idcpi));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionRemove($id)
    {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('mine'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $dataProvider = new CActiveDataProvider('Order');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Lists my orders.
     */
    public function actionMine()
    {
        $dataProvider = new CActiveDataProvider('Order', [
            'criteria' => [
                'with' => ['idprod0'],
                'condition' => 'iduser=' . Yii::app()->User->id . ' AND idinv IS NULL',
                'order' => 'idprod0.priceprod ASC'
            ],
        ]);
        $this->render('mine', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
        $model = new Order('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Order']))
            $model->attributes = $_GET['Order'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    public function actionCheckout()
    {
        $dataProvider = new CActiveDataProvider('Order', [
            'criteria' => [
                'with' => ['idprod0'],
                'condition' => 'iduser=' . Yii::app()->User->id . ' AND idinv IS NULL',
                'order' => 'idprod0.priceprod ASC'
            ],
        ]);
        $this->render('checkout', array(
            'dataProvider' => $dataProvider,
        ));
    }

    public function actionFinish()
    {
        $orders = Order::model()->findAllByAttributes(['iduser' => Yii::app()->User->id]);
        $invoiceCreated = false;
        foreach ($orders as $order) {
            if ($order->idinv == "") {
                if (!$invoiceCreated) {
                    $invoice = new Invoice();
                    $invoice->aprobat = '0';
                    $invoice->save();
                    $idinv = $invoice->idinv;
                    $invoiceCreated = true;
                }
                $order->idinv = $idinv;
                $order->save();
            }
        }
        $this->redirect(['invoice/mine']);
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Order the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model = Order::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Order $model the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'order-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

demos/billing/protected/views/order/_form.php
<?php
/* @var $this OrderController */
/* @var $model Order */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'order-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'iduser'); ?>
		<?php echo $form->textField($model,'iduser'); ?>
		<?php echo $form->error($model,'iduser'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'idprod'); ?>
		<?php echo $form->textField($model,'idprod'); ?>
		<?php echo $form->error($model,'idprod'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

demos/billing/protected/views/order/_index.php
<?php
/* @var $this OrderController */
/* @var $data Order */
?>

<div class="col-md-6">
    <div class="thumbnail well order-checkout">

        <b>User:</b>
        <?= $data->iduser0->fname . " " . $data->iduser0->lname . " (" . $data->iduser0->email . ")" ?>
        <br/>

        <b><?php echo CHtml::encode(Product::model()->getAttributeLabel('nameprod')); ?>:</b>
        <?= Product::model()->productManufacturer($data->idprod) ?>
        <?= CHtml::encode($data->idprod0->nameprod); ?>
        <br/>

        <b><?php echo CHtml::encode(Product::model()->getAttributeLabel('priceprod')); ?>:</b>
        <?php echo CHtml::encode($data->idprod0->priceprod) . Product::$currency; ?>
        <br/>

        <b><?php echo CHtml::encode($data->getAttributeLabel('date')); ?>:</b>
        <?php echo CHtml::encode(Yii::app()->dateFormatter->formatDateTime(CDateTimeParser::parse($data->date, 'yyyy-MM-dd'), 'medium', null)); ?>
        <br/>

        <b><?php echo CHtml::encode(Product::model()->getAttributeLabel('priceprod')); ?>:</b>
        <?php if (Product::productSale($data->idprod) != 0): ?>
            <?php echo Product::productPriceWithSale($data->idprod) . Product::$currency; ?>
            <strike><?php echo CHtml::encode($data->idprod0->priceprod); ?> MDL</strike>
            (-<?php echo Product::productSale($data->idprod) . Sales::$unit; ?>)
        <?php else: ?>
            <?php echo CHtml::encode($data->idprod0->priceprod) . Product::$currency; ?>
        <?php endif; ?>
        <br/>

    </div>
</div>

demos/billing/protected/views/order/_minimal.php
<?php
/* @var $this OrderController */
/* @var $data Order */
?>
<div class="col-md-6">
    <div class="thumbnail well order-checkout">
        <b><?php echo CHtml::encode(Product::model()->getAttributeLabel('nameprod')); ?>:</b>
        <?= Product::model()->productManufacturer($data->idprod) ?>
        <?php echo CHtml::encode($data->idprod0->nameprod); ?>
        <br/>

        <b><?php echo CHtml::encode(Product::model()->getAttributeLabel('priceprod')); ?>:</b>
        <?php echo CHtml::encode($data->idprod0->priceprod); ?> MDL
        <br/>

        <b><?php echo CHtml::encode($data->getAttributeLabel('date')); ?>:</b>
        <?php echo CHtml::encode(Yii::app()->dateFormatter->formatDateTime(CDateTimeParser::parse($data->date, 'yyyy-MM-dd'), 'medium', null)); ?>
        <br/>

        <?php if (Product::productSale($data->idprod) != 0): ?>
            <b><?php echo CHtml::encode(Sales::model()->getAttributeLabel('sale')); ?>:</b>
            <?php echo Product::productSale($data->idprod); ?>%
            <br/>
        <?php endif; ?>

        <b><?php echo CHtml::encode(Product::model()->getAttributeLabel('priceprod')); ?>:</b>
        <?php if (Product::productSale($data->idprod) != 0): ?>
            <?php echo Product::productPriceWithSale($data->idprod); ?> MDL
            <strike><?php echo CHtml::encode($data->idprod0->priceprod); ?> MDL</strike>
        <?php else: ?>
            <?php echo CHtml::encode($data->idprod0->priceprod); ?> MDL
        <?php endif; ?>
        <br/>
    </div>
</div>

demos/billing/protected/views/order/_search.php
<?php
/* @var $this OrderController */
/* @var $model Order */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'idcpi'); ?>
		<?php echo $form->textField($model,'idcpi'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'iduser'); ?>
		<?php echo $form->textField($model,'iduser'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'idprod'); ?>
		<?php echo $form->textField($model,'idprod'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

demos/billing/protected/views/order/_view.php
<?php
/* @var $this OrderController */
/* @var $data Order */
?>

<div class="col-md-6">
    <div class="thumbnail cart-product">
        <div class="options right">
            <?= CHtml::htmlButton('<span aria-hidden="true">&times;</span>',
                [
                    'submit' => array('order/remove?id=' . $data->idcpi),
                    'params' => [
                        'idprod' => $data->idprod
                    ],
                    'confirm' => 'Remove this product?',
                    'class' => 'close',
                    'encode' => false,
                ]
            ) ?>
        </div>

        <b><?php echo CHtml::encode(Product::model()->getAttributeLabel('nameprod')); ?>:</b>
        <?= Product::model()->productManufacturer($data->idprod) ?>
        <?php echo CHtml::encode($data->idprod0->nameprod); ?>
        <br/>

        <b><?php echo CHtml::encode($data->getAttributeLabel('date')); ?>:</b>
        <?php echo CHtml::encode(Yii::app()->dateFormatter->formatDateTime(CDateTimeParser::parse($data->date, 'yyyy-MM-dd'), 'medium', null)); ?>
        <br/>

        <?php if (Product::productSale($data->idprod) != 0): ?>
            <b><?php echo CHtml::encode(Sales::model()->getAttributeLabel('sale')); ?>:</b>
            <?php echo Product::productSale($data->idprod); ?>%
            <br/>
        <?php endif; ?>

        <b><?php echo CHtml::encode(Product::model()->getAttributeLabel('priceprod')); ?>:</b>
        <?php if (Product::productSale($data->idprod) != 0): ?>
            <?php echo Product::productPriceWithSale($data->idprod); ?> MDL
            <s><?php echo CHtml::encode($data->idprod0->priceprod); ?> MDL</s>
        <?php else: ?>
            <?php echo CHtml::encode($data->idprod0->priceprod); ?> MDL
        <?php endif; ?>
        <br/>
    </div>
</div>

demos/billing/protected/views/order/admin.php
<?php
/* @var $this OrderController */
/* @var $model Order */

$this->breadcrumbs=array(
	'Orders'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Order', 'url'=>array('index')),
	array('label'=>'Create Order', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#order-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Orders</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'order-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'idcpi',
		'iduser',
		'idprod',
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

demos/billing/protected/views/order/checkout.php
<?php
/* @var $this OrderController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs = array(
    'Orders',
);

$this->menu = array(
    array('label' => 'Create Order', 'url' => array('create')),
    array('label' => 'Manage Order', 'url' => array('admin')),
);
?>
<h2>Checkout</h2>


<?php $this->widget('zii.widgets.CListView', array(
    'dataProvider' => $dataProvider,
    'itemView' => '_minimal',
)); ?>
<div class="col-md-12">
    <div class="pull-right">
        <p>
            Total: <?= Product::productSumByUser(); ?> MDL
        </p>
        <?= CHtml::link('Finish', ['order/finish'], ['class' => 'btn btn-success pull-right']); ?>
    </div>
</div>

demos/billing/protected/views/order/create.php
<?php
/* @var $this OrderController */
/* @var $model Order */

$this->breadcrumbs=array(
	'Orders'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Order', 'url'=>array('index')),
	array('label'=>'Manage Order', 'url'=>array('admin')),
);
?>

<h1>Create Order</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

demos/billing/protected/views/order/finish.php
<?php
/* @var $this OrderController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs = array(
    'Orders',
);

$this->menu = array(
    array('label' => 'Create Order', 'url' => array('create')),
    array('label' => 'Manage Order', 'url' => array('admin')),
);
?>
<h1>Get invoice</h1>
<h4>Invoice isn't approved yet! Wait until the manager will approve it.</h4>


<?php $this->widget('zii.widgets.CListView', array(
    'dataProvider' => $dataProvider,
    'itemView' => '_minimal',
)); ?>
<h4 class="right2">
    Total: <?= Product::productSumByUser(); ?> MDL
    <br>
    <br>
    <?= CHtml::button('Print',
        [
            'submit' => ['/'],
            'class' => 'right2'
        ]
    ); ?>
</h4>

demos/billing/protected/views/order/index.php
<?php
/* @var $this OrderController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Orders',
);

$this->menu=array(
	array('label'=>'Create Order', 'url'=>array('create')),
	array('label'=>'Manage Order', 'url'=>array('admin')),
);
?>

<h2>All Orders</h2>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_index',
)); ?>

demos/billing/protected/views/order/mine.php
<?php
/* @var $this OrderController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs = array(
    'My cart',
);

$this->menu = array(
    array('label' => 'Create Order', 'url' => array('create')),
    array('label' => 'Manage Order', 'url' => array('admin')),
);
?>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <h2>My cart</h2>
        </div>
    </div>

    <?php if (Product::productSumByUser() > 0): ?>
        <h4>Total: <?= Product::productSumByUser(); ?> MDL</h4>
        <div class="row">
            <?php $this->widget('zii.widgets.CListView', array(
                'dataProvider' => $dataProvider,
                'itemView' => '_view',
            )); ?>
        </div>
        <?= CHtml::button('Checkout',
            [
                'submit' => ['order/checkout'],
                'class' => 'btn btn-success pull-right'
            ]
        ); ?>
    <?php else: ?>
        <p>Is empty</p>
    <?php endif; ?>

</div>

demos/billing/protected/views/order/update.php
<?php
/* @var $this OrderController */
/* @var $model Order */

$this->breadcrumbs=array(
	'Orders'=>array('index'),
	$model->idcpi=>array('view','id'=>$model->idcpi),
	'Update',
);

$this->menu=array(
	array('label'=>'List Order', 'url'=>array('index')),
	array('label'=>'Create Order', 'url'=>array('create')),
	array('label'=>'View Order', 'url'=>array('view', 'id'=>$model->idcpi)),
	array('label'=>'Manage Order', 'url'=>array('admin')),
);
?>

<h1>Update Order <?php echo $model->idcpi; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

demos/billing/protected/views/order/view.php
<?php
/* @var $this OrderController */
/* @var $model Order */

$this->breadcrumbs=array(
	'Orders'=>array('index'),
	$model->idcpi,
);

$this->menu=array(
	array('label'=>'List Order', 'url'=>array('index')),
	array('label'=>'Create Order', 'url'=>array('create')),
	array('label'=>'Update Order', 'url'=>array('update', 'id'=>$model->idcpi)),
	array('label'=>'Delete Order', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->idcpi),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Order', 'url'=>array('admin')),
);
?>

<h1>View Order #<?php echo $model->idcpi; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'idcpi',
		'iduser',
		'idprod',
	),
)); ?>